project_id: "894776"
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true
commit_message: "[skip i18n]"

files:
  - source: /i18n/UnifierTSL.template.pot
    translation: /i18n/%locale_with_underscore%/UnifierTSL.po

  - source: /i18n/TShockAPI.template.pot
    translation: /i18n/%locale_with_underscore%/TShockAPI.po

  - source: /i18n/Atelier.template.pot
    translation: /i18n/%locale_with_underscore%/Atelier.po
